project:
  type: website

website:
  title: "DataFest"
  navbar:
    background: primary
    left:
      - file: index.qmd
        text: "Home"
      - file: about.qmd
        text: "About"
      - file: upcoming-events.qmd
        text: "Upcoming Events"
      - file: resources.qmd
        text: "Resources"
      - file: tutorial.qmd
        text: "Tutorials"
      - file: contact.qmd
        text: "Contact"

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - tutorial.qmd
        - getting-started.qmd
        - eda.qmd
        - regression.qmd
        - hypothesis-testing.qmd

format:
  html:
    theme: zephyr
    css: styles.css

editor: visual

